export const Colors = {
  deepTeal:        "#071D3A",
  darkEmerald:     "#0A2F5C",
  teal:            "#14B8A6",
  softMint:        "#D3FAF3",
  warmIvory:       "#FFFFFF",
  gold:            "#F4B321",
  charcoal:        "#071D3A",
  white:           "#FFFFFF",
  background:      "#FFFFFF",
  foreground:      "#071D3A",
  card:            "#FFFFFF",
  muted:           "#F0F2F6",
  mutedForeground: "#66718E",
  primary:         "#071D3A",
  accent:          "#14B8A6",
  border:          "#DADDE7",
  success:         "#18C86F",
  destructive:     "#DC2626",
  tabBar:          "#FFFFFF",
  tabIconActive:   "#071D3A",
  tabIconInactive: "#66718E",
  tabActiveBg:     "#D3FAF3",
  coral:           "#D86F52",
  paleTeal:        "#D3FAF3",
  paleGold:        "#FFF4D8",
  paleBlue:        "#E9F0FA",
} as const;
