export const Colors = {
  deepTeal:        "#0B3F43",
  darkEmerald:     "#0E5E60",
  teal:            "#17A389",
  softMint:        "#8EEED0",
  warmIvory:       "#F8F3EA",
  gold:            "#D99A2B",
  charcoal:        "#1F2927",
  white:           "#FFFFFF",
  background:      "#F8F3EA",
  foreground:      "#1F2927",
  card:            "#FFFCF7",
  muted:           "#EFE7DA",
  mutedForeground: "#66706D",
  primary:         "#0B3F43",
  accent:          "#17A389",
  border:          "#DDD5C8",
  success:         "#17A389",
  destructive:     "#dc2626",
  tabBar:          "#FFFCF7",
  tabIconActive:   "#0B6159",
  tabIconInactive: "#7B8481",
  tabActiveBg:     "#DDF3EA",
  coral:           "#D86F52",
  paleTeal:        "#DDF3EA",
  paleGold:        "#FAEBCB",
  paleBlue:        "#E2ECF7",
} as const;
