"""add_marketplace_tables

Revision ID: 55c221e21c3e
Revises: a1232e05e4cf
Create Date: 2026-08-24 20:45:04.063142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '55c221e21c3e'
down_revision: Union[str, Sequence[str], None] = 'a1232e05e4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('tutor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=False),
    sa.Column('teaching_mode', sa.String(length=20), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('rate_per_hour', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_hours_taught', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('average_rating >= 0 AND average_rating <= 5', name='ck_tutor_rating_range'),
    sa.CheckConstraint('rate_per_hour >= 0', name='ck_tutor_rate_non_negative'),
    sa.CheckConstraint('review_count >= 0', name='ck_tutor_review_count_non_negative'),
    sa.CheckConstraint('total_hours_taught >= 0', name='ck_tutor_hours_non_negative'),
    sa.CheckConstraint('years_of_experience >= 0', name='ck_tutor_experience_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_profiles_user_id'), 'tutor_profiles', ['user_id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'tutor_id', name='uq_review_student_tutor')
    )
    op.create_index(op.f('ix_reviews_student_id'), 'reviews', ['student_id'], unique=False)
    op.create_index('ix_reviews_tutor_id', 'reviews', ['tutor_id'], unique=False)
    op.create_table('tutor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=15), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_time_range'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tutor_availability_tutor_day', 'tutor_availability', ['tutor_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_tutor_availability_tutor_id'), 'tutor_availability', ['tutor_id'], unique=False)
    op.create_table('tutor_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('rate_override', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.CheckConstraint('rate_override IS NULL OR rate_override >= 0', name='ck_subject_rate_non_negative'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'subject_id', name='uq_tutor_subject')
    )
    op.create_index('ix_tutor_subjects_subject_id', 'tutor_subjects', ['subject_id'], unique=False)
    op.create_index('ix_tutor_subjects_tutor_id', 'tutor_subjects', ['tutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutor_subjects_tutor_id', table_name='tutor_subjects')
    op.drop_index('ix_tutor_subjects_subject_id', table_name='tutor_subjects')
    op.drop_table('tutor_subjects')
    op.drop_index(op.f('ix_tutor_availability_tutor_id'), table_name='tutor_availability')
    op.drop_index('ix_tutor_availability_tutor_day', table_name='tutor_availability')
    op.drop_table('tutor_availability')
    op.drop_index('ix_reviews_tutor_id', table_name='reviews')
    op.drop_index(op.f('ix_reviews_student_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_tutor_profiles_user_id'), table_name='tutor_profiles')
    op.drop_table('tutor_profiles')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
