"""add_education_level

Revision ID: a1232e05e4cf
Revises: 0002_add_phone_number
Create Date: 2026-08-24 14:14:11.959018
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'a1232e05e4cf'
down_revision: Union[str, Sequence[str], None] = '0002_add_phone_number'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education_level', sa.Enum('primary_school', 'junior_secondary', 'senior_secondary', 'high_school', 'undergraduate', 'postgraduate', name='educationlevel'), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'education_level')
    # ### end Alembic commands ###
