"""add_profile_image_url_to_users

Revision ID: a8760d6ddd8a
Revises: 0003_add_billing_tables
Create Date: 2026-08-26 18:07:46.577124
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'a8760d6ddd8a'
down_revision: Union[str, Sequence[str], None] = '0003_add_billing_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
